---
name: test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: aquaproj/aqua-installer@v0.6.0-0
        with:
          aqua_version: v0.10.2
          aqua_opts: --test
