---
name: test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: cache ~/.aqua
        uses: actions/cache@v2
        with:
          path: |
            ~/.aqua/pkgs
            ~/.aqua/registries
          key: ${{ runner.os }}-${{ hashFiles('registry.yaml') }}-${{ hashFiles('aqua.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('registry.yaml') }}-
            ${{ runner.os }}-
      - uses: aquaproj/aqua-installer@main
        with:
          version: v0.8.1 # renovate: depName=aquaproj/aqua

      - run: aqua i --test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
